### ISSUE TITLE
ES SYNAPPS Shared library error

### ISSUE THREAD

**Issue by tjgarci2** [rcthomas/es#10]
Hi, I have installed SYNAPPS AND SYN++ and when attempting to run SYNAPPS in the terminal on my linux machine, I get an error of this sort

tjsgarcia@tgarcia-K55VD:~$ mpirun -np 2 synapps synapp.yaml
synapps: error while loading shared libraries: libappspack.so.0: cannot open shared object file: No such file or directory
synapps: error while loading shared libraries: libappspack.so.0: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------

I was wondering if you could help.

**Comment by tskisner** [comment]
It looks like you installed appspack to a location which is not in
LD_LIBRARY_PATH.  On Linux systems you either need to install software to
standard locations (like /usr/local) or you must add the correct paths to
certain environment variables which control where the dynamic library
loader searches for libraries.

**Comment by tjgarci2** [comment]
Sorry for the late response, I reinstalled both APPSPACK and SYNAPPS with both in usr/local, but it's returning the same error when I run it. I am now wondering how to add the correct paths to
certain environment variables for the dynamic library loader, in other words is there a specific folder I need to edit?
